version: '3.11'


services:
  bot:
    build: .
    restart: always
    container_name: exam_shohjahon
    environment:
      BOT_TOKEN: 6739521733:AAFg6sWfzb61eBs5db8zcu2hr-DFJCmcgtE
      DB_NAME: postgres
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py


  pg:
    image: postgres:alpine
    restart: always
    container_name: contine_shohjahon
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: